Fixing CI workflow

diff --git a/.github/workflows/build-btt-ender3v2.yaml b/.github/workflows/build-btt-ender3v2.yaml
--- a/.github/workflows/build-btt-ender3v2.yaml
+++ b/.github/workflows/build-btt-ender3v2.yaml
@@ -32,7 +32,7 @@ jobs:
 
   build-marlin-firmware:
     ## TODO: Ensure that this works as expected
-    # if: ${{ github.base_ref == 'bugfix-2.0.x' || github.event.inputs.targetBranch == 'bugfix-2.0.x' }}
+    if: ${{ github.base_ref == 'bugfix-2.0.x' || github.event.inputs.targetBranch == 'bugfix-2.0.x' }}
     name: Build Marlin Firmware
     runs-on: ubuntu-latest
     strategy:
@@ -81,162 +81,126 @@ jobs:
         # ui: ["JyersUI", "BIGTREE_TFT35_E3_V3_0"]
     steps:
 
-      # - name: Prepare Target Branch
-      #   if: success() # Ensure we only run this step if the previous one succeeded
-      #   run: |-
-
-      #     # Enable script debugging
-      #     # set -x
-
-      #     # Target branch defaults to base ref
-      #     TARGET_BRANCH=${{ env.GITHUB_BASE_REF }}
-      #     echo "Target branch: $TARGET_BRANCH"
-          
-      #     # If our target branch is not set, default to the "bugfix-2.0.x" branch instead
-      #     if [ -z "${TARGET_BRANCH}" ]; then
-      #       echo "Target branch not available, defaulting to 'bugfix-2.0.x'"
-      #       TARGET_BRANCH=bugfix-2.0.x
-      #     fi
-
-      #     # Allow overriding the target branch with manual builds
-      #     OVERRIDE_TARGET_BRANCH=${{ github.event.inputs.targetBranch }}
-      #     if [ ! -z "${OVERRIDE_TARGET_BRANCH}" ]; then
-      #       echo "Branch override detected, setting branch to: '${OVERRIDE_TARGET_BRANCH}'"
-      #       TARGET_BRANCH=${OVERRIDE_TARGET_BRANCH}
-      #     fi
-
-      #     # If this is a tagged release, always use the "2.0.x" branch instead
-      #     REF_TYPE=${{ env.GITHUB_REF_TYPE }}
-      #     REF_NAME=${{ env.GITHUB_REF_NAME }}
-      #     if [ "$REF_TYPE" = "tag" ]; then
-      #       echo "Release tag detected, setting branch to '2.0.x'"
-      #       echo "TARGET_TAG=${REF_NAME}" >> $GITHUB_ENV
-      #       TARGET_BRANCH=2.0.x
-      #     fi
-
-      #     ## FIXME: Disable/fix this once we have a config that we can actually use with the "2.0.x" branch
-      #     # If the target branch is "2.0.x", echo out an error message and fail the build
-      #     if [ "$TARGET_BRANCH" = "2.0.x" ]; then
-      #       echo "::error title=Unsupported target branch::This workflow is not currently configured to run on the '2.0.x' branch."
-      #       exit 1
-      #     fi
-
-      #     # echo "Final target branch: $TARGET_BRANCH"
-      #     echo "::warning title=Final target branch::$TARGET_BRANCH"
-
-      #     # Ensure that we have a target branch
-      #     if [ -z "${TARGET_BRANCH}" ]; then
-      #       echo "::error title=Missing target branch::Could not detect target branch, unable to continue"
-      #       exit 1
-      #     else
-      #       # Export the final target branch as a global environment variable
-      #       echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
-      #     fi
-
-      #     # exit 1
-
-      - name: Install Dependencies
-        if: success()
-        id: install_dependencies
+      - name: Prepare Target Branch
         run: |-
 
           # Enable script debugging
           set -x
 
-          # Download the latest build setup action
-          mkdir -p mkdir -p .github/workflows/build-setup-action
-          wget \
-            https://raw.githubusercontent.com/Didstopia/Marlin/skr-mini-e3-v3-0/.github/workflows/build-setup-action/action.yml \
-            -O .github/workflows/build-setup-action/action.yml
+          # Target branch defaults to base ref
+          TARGET_BRANCH=${{ github.event.inputs.currentBranch || env.GITHUB_BASE_REF }}
+          echo "Target branch: $TARGET_BRANCH"
+          
+          # If our target branch is not set, default to the "bugfix-2.0.x" branch instead
+          if [ -z "${TARGET_BRANCH}" ]; then
+            echo "Target branch not available, defaulting to 'bugfix-2.0.x'"
+            TARGET_BRANCH=bugfix-2.0.x
+          fi
 
-      - name: Build Setup
-        id: build_setup
-        uses: ./.github/workflows/build-setup-action
+          # Allow overriding the target branch with manual builds
+          OVERRIDE_TARGET_BRANCH=${{ github.event.inputs.targetBranch }}
+          if [ ! -z "${OVERRIDE_TARGET_BRANCH}" ]; then
+            echo "Branch override detected, setting branch to: '${OVERRIDE_TARGET_BRANCH}'"
+            TARGET_BRANCH=${OVERRIDE_TARGET_BRANCH}
+          fi
+
+          # If this is a tagged release, always use the "2.0.x" branch instead
+          REF_TYPE=${{ env.GITHUB_REF_TYPE }}
+          REF_NAME=${{ env.GITHUB_REF_NAME }}
+          if [ "$REF_TYPE" = "tag" ]; then
+            echo "Release tag detected, setting branch to '2.0.x'"
+            echo "TARGET_TAG=${REF_NAME}" >> $GITHUB_ENV
+            TARGET_BRANCH=2.0.x
+          fi
+
+          ## FIXME: Disable/fix this once we have a config that we can actually use with the "2.0.x" branch
+          # If the target branch is "2.0.x", echo out an error message and fail the build
+          if [ "$TARGET_BRANCH" = "2.0.x" ]; then
+            echo "::error title=Unsupported target branch::This workflow is not currently configured to run on the '2.0.x' branch."
+            exit 1
+          fi
+
+          # echo "Final target branch: $TARGET_BRANCH"
+          echo "::warning title=Final target branch::$TARGET_BRANCH"
+
+          # Ensure that we have a target branch
+          if [ -z "${TARGET_BRANCH}" ]; then
+            echo "::error title=Missing target branch::Could not detect target branch, unable to continue"
+            exit 1
+          else
+            # Export the final target branch as a global environment variable
+            echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
+          fi
+
+      - name: Checkout Repository
+        if: success()
+        uses: actions/checkout@v3
         with:
-          currentBranch: ${{ github.base_ref }}
-          targetBranch: ${{ env.github.event.inputs.targetBranch }}
+          ref: ${{ env.TARGET_BRANCH }}
+          persist-credentials: false
 
-      # - name: Checkout Repository
-      #   if: success() # Ensure we only run this step if the previous one succeeded
-      #   uses: actions/checkout@v3
-      #   with:
-      #     ref: ${{ env.TARGET_BRANCH }}
-      #     persist-credentials: false
+      - name: Prepare Environment
+        if: success()
+        run: |-
 
-      # - name: Prepare Environment
-      #   if: success() # Ensure we only run this step if the previous one succeeded
-      #   run: |-
+          # Enable script debugging
+          # set -x
 
-      #     # Enable script debugging
-      #     # set -x
+          # Generate the version based on the branch and commit/tag
+          if [ -z "${TARGET_TAG}" ]; then
+            echo "RELEASE_VERSION=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
+          else
+            echo "RELEASE_VERSION=$(git rev-parse --abbrev-ref HEAD)-${{ env.TARGET_TAG }}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
+          fi
 
-      #     # Generate the version based on the branch and commit/tag
-      #     if [ -z "${TARGET_TAG}" ]; then
-      #       echo "RELEASE_VERSION=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
-      #     else
-      #       echo "RELEASE_VERSION=$(git rev-parse --abbrev-ref HEAD)-${{ env.TARGET_TAG }}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
-      #     fi
+          # Print out the version
+          echo "::notice title=Version::${{ env.RELEASE_VERSION }}"
 
-      #     # Print out the version
-      #     echo "::notice title=Version::${{ env.RELEASE_VERSION }}"
+      - name: Prepare Build Script
+        if: success()
+        id: configure_build_script
+        run: |-
 
-      # - name: Cache pip
-      #   if: success() && env.ACT != 'true'
-      #   uses: actions/cache@v3
-      #   with:
-      #     path: ~/.cache/pip
-      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-pip-
+          # Enable script debugging
+          set -x
 
-      # - name: Cache PlatformIO
-      #   if: success() && env.ACT != 'true'
-      #   uses: actions/cache@v3
-      #   with:
-      #     path: ~/.platformio
-      #     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
+          # Download the latest helper build script
+          mkdir -p .github/workflows/scripts
+          wget \
+            https://raw.githubusercontent.com/Didstopia/Marlin/skr-mini-e3-v3-0/.github/workflows/scripts/configure_build_script.sh \
+            -O .github/workflows/scripts/configure_build_script.sh
 
-      # # WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager.
-      # #          It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
-      # - name: Setup Python
-      #   if: success() # Ensure we only run this step if the previous one succeeded
-      #   uses: actions/setup-python@v3
-      #   # with:
-      #   #   cache: ${{ !env.ACT && 'pip' || '' }}
-      #   ## NOTE: Using specific versions that match Marlin CI workflows
-      #   with:
-      #     python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
-      #     architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
+      - name: Cache pip
+        if: success()
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
 
-      # - name: Install PlatformIO
-      #   if: success() # Ensure we only run this step if the previous one succeeded
-      #   run: |-
+      - name: Cache PlatformIO
+        if: success()
+        uses: actions/cache@v3
+        with:
+          path: ~/.platformio
+          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
 
-      #     # Enable script debugging
-      #     # set -x
+      - name: Setup Python
+        if: success()
+        uses: actions/setup-python@v3
 
-      #     ## NOTE: Using specific versions that match Marlin CI workflows
-      #     python -m pip install --upgrade pip
-      #     pip install --upgrade platformio
-      #     # pip install -U https://github.com/platformio/platformio-core/archive/v5.2.5.zip
-      #     # platformio platform update
-      #     ## NOTE: Now using development versions of PlatformIO Core 6.X
-      #     pio upgrade --dev
-      #     pio pkg update --global
+      - name: Install PlatformIO
+        if: success()
+        run: |-
 
-      # - name: Prepare Build Script
-      #   if: success()
-      #   id: configure_build_script
-      #   run: |-
+          # Enable script debugging
+          set -x
 
-      #     # Enable script debugging
-      #     # set -x
-
-      #     # Download the latest helper build script
-      #     mkdir -p .github/workflows/scripts
-      #     wget \
-      #       https://raw.githubusercontent.com/Didstopia/Marlin/skr-mini-e3-v3-0/.github/workflows/scripts/configure_build_script.sh \
-      #       -O .github/workflows/scripts/configure_build_script.sh
+          python -m pip install --upgrade pip
+          pip install --upgrade platformio
+          pio upgrade --dev
+          pio pkg update --global
 
       - name: Configure Firmware
         if: success()
