Fixing BTT TFT35 compilation step

diff --git a/.github/workflows/build-btt-ender3v2.yaml b/.github/workflows/build-btt-ender3v2.yaml
--- a/.github/workflows/build-btt-ender3v2.yaml
+++ b/.github/workflows/build-btt-ender3v2.yaml
@@ -33,8 +33,8 @@ env:
 
 jobs:
 
-  build-firmwares:
-    name: Build Firmwares
+  build-marlin-firmware:
+    name: Build Marlin Firmware
     runs-on: ubuntu-latest
     strategy:
       # Fail early when possible (only applies to matrix jobs)
@@ -1281,92 +1281,92 @@ jobs:
           MPC: ${{ matrix.mpc }}
           UI: ${{ matrix.ui }}
 
-      ## FIXME: !!! Why do we need to compile the display firmware for EVERY single matrix build, when we could just build it ONCE? !!!
-      - name: Compile BTT Display Firmware
-        if: matrix.ui == 'BIGTREE_TFT35_E3_V3_0'
-        id: compile_btt_firmware
-        run: |-
+      # ## FIXME: !!! Why do we need to compile the display firmware for EVERY single matrix build, when we could just build it ONCE? !!!
+      # - name: Compile BTT Display Firmware
+      #   if: matrix.ui == 'BIGTREE_TFT35_E3_V3_0'
+      #   id: compile_btt_firmware
+      #   run: |-
 
-          # Enable script debugging
-          set -x
+      #     # Enable script debugging
+      #     set -x
 
-          ## TODO: Split or refactor configure_build_script.sh, so we can use its generic error handling
-          ##       and logging capabilities here, as well as in any other situation, without requiring us
-          ##       to always be at the Marlin source root.
+      #     ## TODO: Split or refactor configure_build_script.sh, so we can use its generic error handling
+      #     ##       and logging capabilities here, as well as in any other situation, without requiring us
+      #     ##       to always be at the Marlin source root.
 
-          # Fetch the source code for the BTT display firmware
-          git clone --depth 1 --branch master --single-branch --recurse-submodules https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware.git "/tmp/${UI}"
+      #     # Fetch the source code for the BTT display firmware
+      #     git clone --depth 1 --branch master --single-branch --recurse-submodules https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware.git "/tmp/${UI}"
 
-          # Switch to the source directory
-          cd "/tmp/${UI}"
+      #     # Switch to the source directory
+      #     cd "/tmp/${UI}"
 
-          ## TODO: Store/set the board/display name in the matrix, so we can reuse it here (and elsewhere if necessary)
-          # Compile the firmware
-          platformio run --environment ${UI}
+      #     ## TODO: Store/set the board/display name in the matrix, so we can reuse it here (and elsewhere if necessary)
+      #     # Compile the firmware
+      #     platformio run --environment ${UI}
 
-          ## TODO: Any particular reason we'd even need this?
-          # Remove old binaries and configs
-          find "Copy to SD Card root directory to update/" -name '*.bin' -print -delete
-          find "Copy to SD Card root directory to update/" -name 'config.ini' -print -delete
+      #     ## TODO: Any particular reason we'd even need this?
+      #     # Remove old binaries and configs
+      #     find "Copy to SD Card root directory to update/" -name '*.bin' -print -delete
+      #     find "Copy to SD Card root directory to update/" -name 'config.ini' -print -delete
 
-          ## TODO: Any particular reason we'd even need this?
-          # Copy new binaries and configs
-          find .pio/build/ -name '*.bin' -exec cp -vf '{}' "./Copy to SD Card root directory to update/" ";"
-          find TFT/src/User/ -name 'config.ini' -exec cp -vf '{}' "./Copy to SD Card root directory to update/" ";"
+      #     ## TODO: Any particular reason we'd even need this?
+      #     # Copy new binaries and configs
+      #     find .pio/build/ -name '*.bin' -exec cp -vf '{}' "./Copy to SD Card root directory to update/" ";"
+      #     find TFT/src/User/ -name 'config.ini' -exec cp -vf '{}' "./Copy to SD Card root directory to update/" ";"
 
-          # Customize the firmware, config and/or theme(s)
-          shopt -s extglob
-          displayConfig() {
-            local option=$1
-            local value=$2
-            local config=$3
-            sed -E -i "s/([^ \n]*?)(${option})(\:)([^ ].*|$)/\2\:${value}/g w /tmp/btt_display_config_patch.log" "$config"
-            if [ ! -s /tmp/btt_display_config_patch.log ]; then
-              echo "::error title=ERROR::Failed to enable ${option} in ${config}"
-              exit 1
-            fi
-          }
-          cd "Copy to SD Card root directory to update"
-          displayConfig serial_port "P1:7 P2:0 P3:0 P4:0" config.ini
-          displayConfig emulated_m600 "0" config.ini
-          displayConfig ack_notification "2" config.ini
-          displayConfig files_list_mode "0" config.ini
-          displayConfig persistent_info "1" config.ini
-          displayConfig notification_m117 "1" config.ini
-          displayConfig prog_disp_type "1" config.ini
-          displayConfig layer_disp_type "1" config.ini
-          displayConfig serial_always_on "1" config.ini
-          displayConfig marlin_font_color "2" config.ini
-          displayConfig marlin_title "RASPUTIN" config.ini
-          displayConfig fan_count "3" config.ini
-          displayConfig controller_fan "1" config.ini
-          displayConfig toast_sound "0" config.ini
-          displayConfig lcd_idle_brightness "1" config.ini
-          displayConfig lcd_lock_on_idle "1" config.ini
-          displayConfig knob_led_color "2" config.ini
-          displayConfig custom_label_8 "MPC Autotune" config.ini
-          displayConfig custom_gcode_8 "M306 T \\\n" config.ini
-          cd ..
+      #     # Customize the firmware, config and/or theme(s)
+      #     shopt -s extglob
+      #     displayConfig() {
+      #       local option=$1
+      #       local value=$2
+      #       local config=$3
+      #       sed -E -i "s/([^ \n]*?)(${option})(\:)([^ ].*|$)/\2\:${value}/g w /tmp/btt_display_config_patch.log" "$config"
+      #       if [ ! -s /tmp/btt_display_config_patch.log ]; then
+      #         echo "::error title=ERROR::Failed to enable ${option} in ${config}"
+      #         exit 1
+      #       fi
+      #     }
+      #     cd "Copy to SD Card root directory to update"
+      #     displayConfig serial_port "P1:7 P2:0 P3:0 P4:0" config.ini
+      #     displayConfig emulated_m600 "0" config.ini
+      #     displayConfig ack_notification "2" config.ini
+      #     displayConfig files_list_mode "0" config.ini
+      #     displayConfig persistent_info "1" config.ini
+      #     displayConfig notification_m117 "1" config.ini
+      #     displayConfig prog_disp_type "1" config.ini
+      #     displayConfig layer_disp_type "1" config.ini
+      #     displayConfig serial_always_on "1" config.ini
+      #     displayConfig marlin_font_color "2" config.ini
+      #     displayConfig marlin_title "RASPUTIN" config.ini
+      #     displayConfig fan_count "3" config.ini
+      #     displayConfig controller_fan "1" config.ini
+      #     displayConfig toast_sound "0" config.ini
+      #     displayConfig lcd_idle_brightness "1" config.ini
+      #     displayConfig lcd_lock_on_idle "1" config.ini
+      #     displayConfig knob_led_color "2" config.ini
+      #     displayConfig custom_label_8 "MPC Autotune" config.ini
+      #     displayConfig custom_gcode_8 "M306 T \\\n" config.ini
+      #     cd ..
 
-          # Remove files unrelated specifically to the display model
-          rm -fr "Copy to SD Card root directory to update/THEME_*/!(${UI})"
+      #     # Remove files unrelated specifically to the display model
+      #     rm -fr "Copy to SD Card root directory to update/THEME_*/!(${UI})"
 
-          # Prepare the build artifact directory
-          # BTT_DIST_DIR="${GITHUB_WORKSPACE}/temp/${{ steps.compile_marlin_firmware.outputs.name }}/${UI}"
-          BTT_DIST_DIR="${GITHUB_WORKSPACE}/temp/build/${UI}"
-          mkdir -p "${BTT_DIST_DIR}"
+      #     # Prepare the build artifact directory
+      #     # BTT_DIST_DIR="${GITHUB_WORKSPACE}/temp/${{ steps.compile_marlin_firmware.outputs.name }}/${UI}"
+      #     BTT_DIST_DIR="${GITHUB_WORKSPACE}/temp/build/${UI}"
+      #     mkdir -p "${BTT_DIST_DIR}"
 
-          # Include built files with the build artifacts
-          cp -R "Copy to SD Card root directory to update/" "${BTT_DIST_DIR}"
+      #     # Include built files with the build artifacts
+      #     cp -R "Copy to SD Card root directory to update/" "${BTT_DIST_DIR}"
 
-          ls -lah ${BTT_DIST_DIR}
+      #     ls -lah ${BTT_DIST_DIR}
 
-          ## FIXME: For some reason the artifact uploads are failing when including the BTT display files,
-          ##        but the HTTP requests also seem to set "itemPath" as the firmware name,
-          ##        except it includes the path TWICE for some reason?!
+      #     ## FIXME: For some reason the artifact uploads are failing when including the BTT display files,
+      #     ##        but the HTTP requests also seem to set "itemPath" as the firmware name,
+      #     ##        except it includes the path TWICE for some reason?!
 
-        env:
-          UI: ${{ matrix.ui }}
+      #   env:
+      #     UI: ${{ matrix.ui }}
 
       - name: Publish Artifacts
         ## FIXME: Artifact uploading is broken with act, the server doesn't work, so disabling for now
