Added BTT display config patches etc.

diff --git a/.github/workflows/build-btt-ender3v2.yaml b/.github/workflows/build-btt-ender3v2.yaml
--- a/.github/workflows/build-btt-ender3v2.yaml
+++ b/.github/workflows/build-btt-ender3v2.yaml
@@ -74,9 +74,9 @@ jobs:
         mpc: [true, false]
         # mpc: [false]
         # ui: ["JyersUI", "MarlinUI"]
-        ui: ["JyersUI", "MarlinUI", "TFT35"]
-        # TODO: Enable this once we have time to test out the BTT's TFT35 display
-        # ui: ["JyersUI", "TFT35"]
+        ui: ["JyersUI", "MarlinUI", "BIGTREE_TFT35_E3_V3_0"]
+        # TODO: Enable this once we have time to test out the BTT's BIGTREE_TFT35_E3_V3_0 display
+        # ui: ["JyersUI", "BIGTREE_TFT35_E3_V3_0"]
     steps:
 
       - name: Checkout Repository
@@ -662,7 +662,7 @@ jobs:
             #        so keep trying and perhaps even try without linear advance and/or junction deviation?
             configValue DEFAULT_EJERK 5.0 Marlin/Configuration.h
 
-            if [ $UI == "TFT35" ]; then
+            if [ $UI == "BIGTREE_TFT35_E3_V3_0" ]; then
               ## FIXME: People are saying that S-Curve does NOT work well with linear advance,
               ##        so we're giving it a go without it, see how that pans out!
               configDisable S_CURVE_ACCELERATION Marlin/Configuration.h
@@ -676,7 +676,7 @@ jobs:
           ##        we should be able to use this with eg. Marlin UI, right?
           # NOTE: MPC is still HIGHLY experimental, proceed with caution!
           if ($MPC); then
-            if [ $UI == "TFT35" ]; then
+            if [ $UI == "BIGTREE_TFT35_E3_V3_0" ]; then
               # Disable PID and enable MPC
               configDisable PIDTEMP Marlin/Configuration.h
               configEnable MPCTEMP Marlin/Configuration.h
@@ -712,9 +712,7 @@ jobs:
             # Disable Marlin UI
             configDisable DWIN_MARLINUI_PORTRAIT Marlin/Configuration.h
             configDisable DWIN_MARLINUI_LANDSCAPE Marlin/Configuration.h
-          elif [ $UI == "TFT35" ]; then
-            # TODO: Implement BTT TFT35 support here
-            ## TODO: We probably want Marlin UI with the BTT screen, right? Portrait or landscape? Probably landscape, right?
+          elif [ $UI == "BIGTREE_TFT35_E3_V3_0" ]; then
             configDisable DWIN_MARLINUI_PORTRAIT Marlin/Configuration.h
             configDisable DWIN_MARLINUI_LANDSCAPE Marlin/Configuration.h
 
@@ -731,8 +729,7 @@ jobs:
             configValue LCD_FEEDBACK_FREQUENCY_DURATION_MS 20 Marlin/Configuration.h
             configValue LCD_FEEDBACK_FREQUENCY_HZ 5000 Marlin/Configuration.h
 
-            ## TODO: Experimental options for enabling the BTT TFT35 display
-            # configEnable BTT_TFT35_SPI_V1_0 Marlin/Configuration.h
+            ## TODO: Experimental options for enabling the BTT BIGTREE_TFT35_E3_V3_0 display
             configEnable CR10_STOCKDISPLAY Marlin/Configuration.h
             # configEnable TFT_COLOR_UI Marlin/Configuration.h
             # configEnable TOUCH_SCREEN Marlin/Configuration.h
@@ -1177,7 +1174,7 @@ jobs:
 
               ## FIXME: People are saying that S-Curve does NOT work well with linear advance,
               ##        so we're giving it a go without it, see how that pans out!
-              if [$UI == "TFT35"]; then
+              if [$UI == "BIGTREE_TFT35_E3_V3_0"]; then
                 configDisable EXPERIMENTAL_SCURVE Marlin/Configuration_adv.h
               else
                 configEnable EXPERIMENTAL_SCURVE Marlin/Configuration_adv.h
@@ -1196,7 +1193,7 @@ jobs:
             configEnable G29_RETRY_AND_RECOVER Marlin/Configuration_adv.h
           fi
 
-          if [ $UI == "TFT35" ]; then
+          if [ $UI == "BIGTREE_TFT35_E3_V3_0" ]; then
             # Enable additional reporting etc. features
             configEnable AUTO_REPORT_POSITION Marlin/Configuration_adv.h
             configEnable M115_GEOMETRY_REPORT Marlin/Configuration_adv.h
@@ -1205,6 +1202,11 @@ jobs:
             configEnable REPORT_FAN_CHANGE Marlin/Configuration_adv.h
             configEnable AUTO_REPORT_SD_STATUS Marlin/Configuration_adv.h
             configValue SERIAL_FLOAT_PRECISION 4 Marlin/Configuration_adv.h
+
+            ## FIXME: According to a review on Amazon, ULTIPANEL_FEEDMULTIPLY needs to be disabled,
+            ##        otherwise the encoder gets triggered by even the slightest vibrations of the printer,
+            ##        which is immediately apparent when the display is mounted on the printer.
+            configDisable ULTIPANEL_FEEDMULTIPLY Marlin/Configuration_adv.h
           fi
 
           ## END OF CONFIGURATION_ADV.H
@@ -1237,7 +1239,7 @@ jobs:
           if ($JUNCTION_DEVIATION); then JUNCTION_DEVIATION_LABEL=-JUNCTION_DEVIATION; else JUNCTION_DEVIATION_LABEL=-CLASSIC_JERK; fi;
           if ($HYBRID_THRESHOLD); then HYBRID_THRESHOLD_LABEL=-HYBRID_THRESHOLD; else HYBRID_THRESHOLD_LABEL=; fi;
           if ($MPC); then MPC_LABEL=-MPC; else MPC_LABEL=-PID; fi;
-          FIRMWARE_NAME="ENDER_E3_V2-${BOARD}${UI_LABEL}${BLTOUCH_LABEL}${UBL_LABEL}${GRID}x${GRID}${HS_LABEL}${DD_LABEL}${LINEAR_ADVANCE_LABEL}${JUNCTION_DEVIATION_LABEL}${HYBRID_THRESHOLD_LABEL}${MPC_LABEL}-${VERSION}"
+          FIRMWARE_NAME="ENDER_E3_V2-${BOARD}${UI_LABEL}${BLTOUCH_LABEL}${UBL_LABEL}-${GRID}x${GRID}${HS_LABEL}${DD_LABEL}${LINEAR_ADVANCE_LABEL}${JUNCTION_DEVIATION_LABEL}${HYBRID_THRESHOLD_LABEL}${MPC_LABEL}-${VERSION}"
           echo "::set-output name=name::${FIRMWARE_NAME}"
           echo "::set-output name=filename::${FIRMWARE_NAME}.bin"
 
@@ -1252,16 +1254,14 @@ jobs:
           cp Marlin/Configuration.h "temp/${FIRMWARE_NAME}/Configuration.h"
           cp Marlin/Configuration_adv.h "temp/${FIRMWARE_NAME}/Configuration_adv.h"
 
-          ## TODO: !!! Add DWIN customizations here !!!
-
-          ## TODO: !!! Add BTT TFT35 customizations (possibly even compilation?) here, copy built firmware, config and themes also? !!!
+          ## TODO: Add DWIN customizations here?
 
           # Include the latest DWIN display firmware with all build artifacts
-          if [ $UI != "TFT35" ]; then
+          if [ $UI != "BIGTREE_TFT35_E3_V3_0" ]; then
             cp -R "Configurations/config/examples/Creality/Ender-3 V2/LCD Files/DWIN_SET" "temp/${FIRMWARE_NAME}/DWIN_SET"
             cp -R "Configurations/config/examples/Creality/Ender-3 V2/LCD Files/private" "temp/${FIRMWARE_NAME}/private"
           else
-            echo "::warning::TFT35 UI detected, skipping DWIN files"
+            echo "::warning::BIGTREE_TFT35_E3_V3_0 UI detected, skipping DWIN files"
           fi
 
         env:
@@ -1278,26 +1278,27 @@ jobs:
           MPC: ${{ matrix.mpc }}
           UI: ${{ matrix.ui }}
 
-      - name: Compile BTT TFT35 Firmware
-        if: matrix.ui == 'TFT35'
-        id: compile_btt_tft35_firmware
+      - name: Compile BTT Display Firmware
+        if: matrix.ui == 'BIGTREE_TFT35_E3_V3_0'
+        id: compile_btt_firmware
         run: |-
 
           # Enable script debugging
-          set -x
+          # set -x
 
           ## TODO: Split or refactor configure_build_script.sh, so we can use its generic error handling
           ##       and logging capabilities here, as well as in any other situation, without requiring us
           ##       to always be at the Marlin source root.
 
-          # Fetch the source code for the TFT35 firmware
-          git clone --depth 1 --branch master --single-branch --recurse-submodules https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware.git /tmp/btt-tft35
+          # Fetch the source code for the BTT display firmware
+          git clone --depth 1 --branch master --single-branch --recurse-submodules https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware.git "/tmp/${DISPLAY_MODEL}"
 
           # Switch to the source directory
-          cd /tmp/btt-tft35
+          cd "/tmp/${DISPLAY_MODEL}"
 
+          ## TODO: Store/set the board/display name in the matrix, so we can reuse it here (and elsewhere if necessary)
           # Compile the firmware
-          platformio run --environment BIGTREE_TFT35_E3_V3_0
+          platformio run --environment ${UI}
 
           ## TODO: Any particular reason we'd even need this?
           # Remove old binaries and configs
@@ -1309,12 +1310,52 @@ jobs:
           find .pio/build/ -name '*.bin' -exec cp -vf '{}' "./Copy to SD Card root directory to update/" ";"
           find TFT/src/User/ -name 'config.ini' -exec cp -vf '{}' "./Copy to SD Card root directory to update/" ";"
 
+          # Customize the firmware, config and/or theme(s)
+          shopt -s extglob
+          BTT_CONF_FILE="/tmp/${DISPLAY_MODEL}/Copy to SD Card root directory to update/config.ini"
+          displayConfig() {
+            local option=$1
+            local value=$2
+            local config=$3
+            sed -E -i "s/([^ \n]*?)(${option})(\:)([^ ].*|$)/\2\:${value}/g w /tmp/btt_display_config_patch.log" ${config}
+            if [ ! -s /tmp/btt_display_config_patch.log ]; then
+              echo "::error title=ERROR::Failed to enable ${option} in ${config}"
+              exit 1
+            fi
+          }
+          displayConfig serial_port "P1:7 P2:0 P3:0 P4:0" ${BTT_CONF_FILE}
+          displayConfig emulated_m600 "0" ${BTT_CONF_FILE}
+          displayConfig ack_notification "2" ${BTT_CONF_FILE}
+          displayConfig files_list_mode "0" ${BTT_CONF_FILE}
+          displayConfig persistent_info "1" ${BTT_CONF_FILE}
+          displayConfig notification_m117 "1" ${BTT_CONF_FILE}
+          displayConfig prog_disp_type "1" ${BTT_CONF_FILE}
+          displayConfig layer_disp_type "1" ${BTT_CONF_FILE}
+          displayConfig serial_always_on "1" ${BTT_CONF_FILE}
+          dislayConfig marlin_font_color "2" ${BTT_CONF_FILE}
+          displayConfig marlin_title "RASPUTIN" ${BTT_CONF_FILE}
+          displayConfig fan_count "3" ${BTT_CONF_FILE}
+          displayConfig controller_fan "1" ${BTT_CONF_FILE}
+          displayConfig toast_sound "0" ${BTT_CONF_FILE}
+          displayConfig lcd_idle_brightness "1" ${BTT_CONF_FILE}
+          displayConfig lcd_lock_on_idle "1" ${BTT_CONF_FILE}
+          displayConfig knob_led_color "2" ${BTT_CONF_FILE}
+          displayConfig custom_label_8 "MPC Autotune" ${BTT_CONF_FILE}
+          displayConfig custom_gcode_8 "M306 T \\\n" ${BTT_CONF_FILE}
+
+          # Remove files unrelated specifically to the display model
+          # rm -fr Copy\ to\ SD\ Card\ root\ directory\ to\ update/THEME_*/!(${UI})
+          rm -fr "Copy to SD Card root directory to update/THEME_*/!(${UI})"
+
           # Prepare the build artifact directory
-          BTT_DIST_DIR="${GITHUB_WORKSPACE}/temp/${{ steps.compile_marlin_firmware.outputs.name }}/btt-tft35"
+          BTT_DIST_DIR="${GITHUB_WORKSPACE}/temp/${{ steps.compile_marlin_firmware.outputs.name }}/${UI}"
           mkdir -p "${BTT_DIST_DIR}"
 
           # Include built files with the build artifacts
           cp -R "Copy to SD Card root directory to update" "${BTT_DIST_DIR}/"
+
+        env:
+          UI: ${{ matrix.ui }}
 
       - name: Publish Artifacts
         ## FIXME: Artifact uploading is broken with act, the server doesn't work, so disabling for now
